# permissions for end users to edit ldapuseraccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ldapuseraccount-editor-role
rules:
- apiGroups:
  - ldap.digitalis.io
  resources:
  - ldapuseraccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ldap.digitalis.io
  resources:
  - ldapuseraccounts/status
  verbs:
  - get
