# permissions for end users to edit ldapgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ldapgroup-editor-role
rules:
- apiGroups:
  - ldap.digitalis.io
  resources:
  - ldapgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ldap.digitalis.io
  resources:
  - ldapgroups/status
  verbs:
  - get
