
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ldap.digitalis.io
  resources:
  - ldapgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ldap.digitalis.io
  resources:
  - ldapgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ldap.digitalis.io
  resources:
  - ldapusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ldap.digitalis.io
  resources:
  - ldapusers/status
  verbs:
  - get
  - patch
  - update
